FACILITY_GROUPING_MAP = {

    # Non-liquid Biofuels Assets
    "Biogas plant": "Non-liquid Biofuels Assets",
    "Biomethane plant": "Non-liquid Biofuels Assets",
    "LNG terminal": "Non-liquid Biofuels Assets",
    "Liquefaction Plant": "Non-liquid Biofuels Assets",

    # LCF Trading Liquid Biofuels Assets
    "Biodiesel plant": "LCF Trading Liquid Biofuels Assets",
    "Co-Processing plant": "LCF Trading Liquid Biofuels Assets",
    "Ethanol plant": "LCF Trading Liquid Biofuels Assets",
    "ETBE plant": "LCF Trading Liquid Biofuels Assets",
    "MTBE plant": "LCF Trading Liquid Biofuels Assets",
    "HEFA plant": "LCF Trading Liquid Biofuels Assets",
    "HVO plant": "LCF Trading Liquid Biofuels Assets",

    # Feedstock for Biofuels Companies
    "Central Office (Farms/Plantations)": "Feedstock for Biofuels Companies",
    "Central Office (FarmsPlantations)": "Feedstock for Biofuels Companies",
    "Central Office (Group of Point of Origin)": "Feedstock for Biofuels Companies",
    "Central Office (Group of FA)": "Feedstock for Biofuels Companies",
    "Central Office of independent Smallholders": "Feedstock for Biofuels Companies",
    "Collecting Point": "Feedstock for Biofuels Companies",
    "Farm / Plantation": "Feedstock for Biofuels Companies",
    "Farm Plantation": "Feedstock for Biofuels Companies",
    "First Gathering Point": "Feedstock for Biofuels Companies",
    "Food processing plant": "Feedstock for Biofuels Companies",
    "Melting plant": "Feedstock for Biofuels Companies",
    "Oil mill": "Feedstock for Biofuels Companies",
    "Other conversion unit": "Feedstock for Biofuels Companies",
    "Point of Origin": "Feedstock for Biofuels Companies",
    "Pulp mill": "Feedstock for Biofuels Companies",
    "Pyrolysis plant": "Feedstock for Biofuels Companies",
    "Sugar mill": "Feedstock for Biofuels Companies",
    "Treatment plant for waste/residues": "Feedstock for Biofuels Companies",
    "Treatment plant for waste residues": "Feedstock for Biofuels Companies",
    "Biomarine Fuel Operator": "Feedstock for Biofuels Companies",

    # Other Processing Plants/Units
    "Compounding plant": "Other Processing Plants/Units",
    "Converter": "Other Processing Plants/Units",
    "Mechanical Recycling Plant": "Other Processing Plants/Units",
    "Polymerization plant": "Other Processing Plants/Units",
    "Refinery": "Other Processing Plants/Units",
    "Cracker": "Other Processing Plants/Units",
    "Crushing plant": "Other Processing Plants/Units",
    "Final Product Refinement": "Other Processing Plants/Units",
    "Forest sourcing area": "Other Processing Plants/Units",
    "Warehouse": "Other Processing Plants/Units",

    # Transport & Logistics Companies
    "Logistics Center": "Transport & Logistics Companies",
    "Transport Company": "Transport & Logistics Companies",

    # Electricity Assets
    "Installation producing energy (electricity, heating or cooling) from bioliquids": "Electricity Assets",
    "Installation producing energy (electricity, heating or cooling) from solid biomass": "Electricity Assets",
    "Installation producing energy (electricity , heating or cooling) from solid biomass": "Electricity Assets",
    "Installation producing energy (electricity, heating or cooling) from biogas": "Electricity Assets",
    "Installation producing energy (electricity, heating or cooling) from raw biogas": "Electricity Assets",
    "Installation producing energy (electricity, heating or cooling) from biomethane": "Electricity Assets",
    "Installation producing energy (electricity , heating or cooling) from liquid biomass":"Electricity Assets",
    "Installation producing energy (electricity , heating or cooling) bioliquids": "Electricity Assets",
    "Installation producing energy (electricity , heating or cooling) from biomethane": "Electricity Assets",


    # E-Fuels / RFNBO Assets
    "Electrolyser": "E-Fuels / RFNBO Assets",
    "Methanol plant": "E-Fuels / RFNBO Assets",
    "Installation Consuming RFNBOs": "E-Fuels / RFNBO Assets",

    # Chemicals Assets
    "Plastic Waste Processor": "Chemicals Assets",
    "Plastic waste processor": "Chemicals Assets",
    "Speciality Chemical Plant": "Chemicals Assets",
    "Specialty chemical plant": "Chemicals Assets",

    # Trading Companies
    "Proof of Compliance Trader": "Trading Companies",
    "Trader": "Trading Companies",
    "Trader with Storage": "Trading Companies",
}

MANUAL_COUNTRY_OVERRIDES = {
    "Republic Of": "South Korea",
    "Republic of": "South Korea", 
    "Province of China": "Taiwan",
    "Bolivarian Republic of": "Venezuela",
    "Ireland": "Republic of Ireland",
    "Viet Nam": "Vietnam",
    "Macedonia": "North Macedonia",
    "Russian Federation": "Russia",
    "Côte d'Ivoire": "Ivory Coast",
    "The Netherlands": "Netherlands",
    "British": "British Virgin Islands",
    "Islamic Republic of": "Iran",
    "Lettland": "Latvia",
    "Libyan Arab Jamahiriya": "Libya",
    "Reunion": "Réunion",
    "Swaziland": "Eswatini",
    "United Republic of": "Tanzania",
    "Slowakei": "Slovakia",
    "Hong Kong": "China"
}

CERTIFICATE_TYPE_MAP = {
    "ISCC EU": "Mandated",
    "ISCC PLUS": "Voluntary",
    "ISCC JAPAN": "Japan FIT",
    "ISCC CORSIA": "Aviation",
    "ISCC CFC": "Carbon Footprint Certification",
    "DE B BLE BM": "Legacy"
}


COLUMN_MAP = {
    "cert_number": "Certificate_ID",
    "cert_owner": "Certificate_Holder",
    "cert_scope": "Scope",
    "cert_processingunittype": "Processing_Unit_Type",
    "cert_in_put": "Raw_Material",
    "cert_add_on": "Add-ons** /CTS",
    "cert_products": "Products",
    "cert_valid_from": "Valid_From",
    "cert_valid_until": "Valid_Until",
    "cert_suspended_date": "Suspended",
    "cert_issuer": "Issuing_CB",
    "cert_map": "Map",
    "cert_file": "Certificate",
    "cert_audit": "Audit_Report",
    "cert_status": "Status"
}


LEGAL_SUFFIXES = {
    "bv","sa","gmbh","llc","ltd","ltda","co","company","ag","oy","kft",
    "sp","zoo","inc","corp","sro","as", "sas", "sdn", "bhd", "tbk", "pvt",
    "asb", "pte", "nv", "sau", "srl", "nv"
}

STOPWORDS = {
    # generic facility words
    "site","plant","facility","factory","works","complex",
    "terminal","depot","storage","warehouse","hub", "products",
    "unit","phase","project","production","processing","operations",
    "operation", "chem", "chemical", "chemicals", "fuels", "petrochemicals",
    "refining", "petrochemical", "additives", "raffinage", "raffinerie", "fluids",
    "plastic", "recycling",

    # transport / port
    "port","harbor","harbour","dock","jetty","berth","quay",
    "tank","tanks","tankfarm","pipeline","loading","unloading",
    "import","export","bunker","bunkering", "marine",

    # address words
    "street","st","road","rd","avenue","ave","lane","ln","way","drive","dr","boulevard","blvd","place","pl",
    "building","bldg","block","floor","suite","industrial","estate","zone","park","area",

    # generic org words
    "group","holding","holdings","international","global","services","solutions","resources","energy", "oil",
    "bio", "global", "renewable", "trading", "industrial", "industria", "industries", "service", "technologies",
    "company", "marketing", "limited", "bioenergy", "special", "biofuels",

    # generic geography words
    "city","town","village","district","region","province",
    "north","south","east","west","central", "paulo", "santo", "san",

    # filler
    "and","of","the","for","in","at","by","on", "la", "de", "pt", "el", "del", "los", "las", "da", "do", "dos", "van", "von"
}

CITY_STOPWORDS = {
   # generic facility words
    "site","plant","facility","factory","works","complex",
    "terminal","depot","storage","warehouse","hub", "products",
    "unit","phase","project","production","processing","operations",
    "operation", "chem", "chemical", "chemicals", "fuels", "petrochemicals",
    "refining", "petrochemical", "additives", "raffinage", "raffinerie", "fluids",

   # transport / port
    "port","harbor","harbour","dock","jetty","berth","quay",
    "tank","tanks","tankfarm","pipeline","loading","unloading",
    "import","export","bunker","bunkering", "marine",

    # generic org words
    "group","holding","holdings","international","global","services","solutions","resources","energy", "oil",
    "bio", "global", "renewable", "trading", "industrial", "industria", "industries", "service", "technologies",
    "company", "marketing", "limited", "bioenergy", "special", "biofuels",

    # address words
    "street","st","road","rd","avenue","ave","lane","ln","way","drive","dr","boulevard","blvd","place","pl",
    "building","bldg","block","floor","suite","industrial","estate","zone","area",

    # special characters
    "&"
}

ALL_COUNTRIES = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "Andorra": "AD",
    "Angola": "AO",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cabo Verde": "CV",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo (Congo-Brazzaville)": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Democratic Republic of the Congo": "CD",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Grenada": "GD",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Micronesia": "FM",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "North Korea": "KP",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Korea": "KR",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatican City": "VA",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
}

# total = 88092